kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  podSubnet: "10.199.0.0/16"
  serviceSubnet: "10.200.0.0/16"
nodes:
- role: control-plane
  image: kindest/node:v1.31.0
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "10.10.10.10"
    protocol: tcp
- role: worker
  image: kindest/node:v1.31.0
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "10.10.10.10"
    protocol: tcp
- role: worker
  image: kindest/node:v1.31.0
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "10.10.10.10"
    protocol: tcp